### ISSUE TITLE
TODO: things that must be done ...

### ISSUE THREAD

**Issue by stufield** [stufield/git-hooks#1]
## Lochview

- [x] open joint escrow account (tax + insurance + HOA)
- [x] set up Morning Owl Properties, LLC
- [x] open joint account for LLC
- [x] set up SimpliSafe account
- [ ] deck contract, permits, down payment
- [x] call plumber about garage drain
- [ ] set up revocable trust
- [x] schedule movers (Billy Goat), Sept. 1, 2022
- [x] change ELCO water company; bill Denney until 09-01
- [x] cancel or transfer TDS
- [x] transfer DISH Network
- [x] set up Rise Broadband
- [x] set up router for Rise Broadband (post-move)
- [x] set up autopay for Rise Broadband (-$5)
- [ ] open Heloc  with Ron USBank
- [x] clean up and simplify coax cables from home exterior
- [x] sweep and clean garage

## Stonecrest

- [ ] transfer home insurance to Farmers for Stonecrest
- [x] get lease contract from Bret
- [x] paint single wall in master bathroom
- [x] schedule final cleaning
- [x] post pictures for rental
- [x] set up rental Sept. 1, 2022
- [x] set up home warranty
- [x] shower renovation contractor
- [x] door frame contractor for laundry door
- [ ] call plumber about rust-colored water in master bath
- [x] dry wall basement landing
- [x] cut out cat pee in drywall
- [x] paint basement walls
- [ ] carpet to basement stairs
- [x] finish front door
- [ ] baseboards in basement landing
- [ ] paint exterior south wall siding
- [ ] take care of wasps nest in front-east downspout
- [ ] south gutter has bow/hump in it ... also need a kick-out installed
- [ ] gutter sealant in south-east gutter
- [x] hook up fire alarm master bedroom

## Address Changes

- [x] USPS
- [x] SomaLogic & CSU
- [x] USCIS
- [x] CapitalOne
- [x] BMO Investments
- [x] REI Credit Card
- [x] Wells Fargo
- [x] Vanguard
- [x] Southwest
- [x] eBay
- [x] Amazon
- [x] Apple
